name: Node.js CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v**'
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build, lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test

  container-image-release:
    name: Make container image release
    needs: [build-and-test]
    uses: nrkno/sofie-github-workflows/.github/workflows/container-build-push.yml@main

